---
name: Class-Inflate
version: 0.05
author:
  - 'kolibrie <kolibrie@cpan.org>'
abstract: Inflate HASH Object from Values in Database
license: perl
requires:
  Devel::Messenger: 0
build_requires:
  DBD::SQLite: 0
  Test::Debugger: 0
provides:
  Class::Inflate:
    file: lib/Class/Inflate.pm
    version: 0.05
generated_by: Module::Build version 0.26
