--- #YAML:1.0
name: Class-Inflate
version: 0.01
author:
  - kolibrie <kolibrie@cpan.org>
abstract: Inflate HASH Object from Values in Database
license: unknown
generated_by: Module::Build version 0.261, without YAML.pm
